version: "2"

linters:
  enable:
    - errcheck
    - govet
    - staticcheck
    - unused
    - ineffassign
    - gocritic
    - misspell

formatters:
  enable:
    - gofumpt

issues:
  exclude-dirs:
    - bin
    - tmp
    - vendor
